### ISSUE TITLE
Streaming service: Anime on Demand

### ISSUE THREAD

**Issue by LastOrDefault** [leonekmi/scrobbly#13]
Anime On Demand is a legal german streaming service for anime. Could you add it to the supported websites?
[Anime On Demand](https://www.anime-on-demand.de)

**Comment by leonekmi** [comment]
Hey LastOrDefault,

I'm sorry to be so late, but now i'm ready to work on AnimeOnDemand, i'm from France, so it will be a little harder espically because AOD applies GeoIP restrict, but i have a German VPN on the hand!

Thanks for your issue!
