### ISSUE TITLE
Streaming service: Hulu

### ISSUE THREAD

**Issue by leonekmi** [leonekmi/scrobbly#16]
Hulu is a streaming service available in U.S.A., it is paid and it doesn't have free option (the free trial need a credit card input).

**Help wanted** : I need access to a Hulu account.

**Comment by theo33500** [comment]
si t'a besoin d'une CB pour l'essais gratuit j'ai mes virtualis 👀

**Comment by samjaninf** [comment]
I responded on Twitter I believe. Dunno if you have checked it yet. Has creds. Let me know if you need premium for longer. @leonekmi

**Comment by leonekmi** [comment]
Thanks @samjaninf, with your Hulu account, 21e68d9a620b661dfe732aeb3de6c31772b2adf1 will be pushed in a next release !
