### ISSUE TITLE
Wakanim DE

### ISSUE THREAD

**Issue by Zunv** [leonekmi/scrobbly#19]
The Website is called Wakanim. Its already implemented BUT only the french Version.
I looked into the Source Code and found this line:
`this.urlregex = /https:\/\/www.wakanim.tv\/fr\/v2\/catalogue\/episode\/([a-zA-Z0-9-]+)\/([a-zA-Z0-9-]+)/;`

I think to get it work in germany it should "just" switch www.wakanim.tv\/fr to www.wakanim.tv\/de
The rest of the url should be the same
Example: 
https://www.wakanim.tv/de/v2/catalogue/episode/8145/kaguya-sama-love-is-war-omu-staffel-1-folge-1-omu

Would be awesome if you can get this to work!

**Comment by leonekmi** [comment]
It was corrected in https://github.com/leonekmi/scrobbly/commit/564c9ce649f13e92faa622dd2481c25b4601a73a and https://github.com/leonekmi/scrobbly/commit/b4c0ebb149b4a06d2f6e6bde294f4b73d9f7caab but i mistyped the issue number. This will be patched in the next release!
Thanks for the feedback! :smile:
