### ISSUE TITLE
[Crunchyroll] Watching anime in fullscreen mode only ever triggers the anilist scrobbler after exiting fullscreen

### ISSUE THREAD

**Issue by moka491** [leonekmi/scrobbly#2]
I think this is mainly a "problem" with how Crunchyroll works and not with your extension per se.
When watching anime on Crunchyroll, and switching to full screen, 
instead of going to another page, the Crunchyroll web player will load the next episode directly,
and thus won't trigger the scrobbling on the next episode. Only when leaving full screen,
it will jump to the new page of the currently watched episode.

That in turn means, if you start at episode one, it will probably still scrobble it, as you have gone to that particular episode page for watching it. But when you entered full screen mode there, watched all episodes up to say episode 5 and then leave the full screen, it will let the browser load the page for episode 5, and the scrobbler will scrobble this one. So in the end, you only scrobbled Ep1 and Ep5.

As mentioned, it's not really an issue, as it would still be tracked correctly on anilist (watched 5 episodes in the end), but if it was possible to track the other ones as well somehow, this would make it look better in status feeds, as the feed would say "AnukWolf (that's me btw ;)) watched episode 1-5 of.." instead of "AnukWolf watched episode 1" and "AnukWolf watched episode 5".

**Comment by leonekmi** [comment]
Due to the nature of the Crunchyroll player (flash player :disappointed:), i don't think i can track for this with JS, and i cannot try with the beta HTML5 player, i don't have a Crunchyroll Premium+ account. I see for a workaround.

**Comment by Deterio** [comment]
I have a CR account, contact me via [Steam](https://steamcommunity.com/id/yx1) or [AL](https://anilist.co/user/Deterio)

**Comment by JannisBecker** [comment]
Update on this one: I don't know _what_ you have done in the latest update,
but this seems to be resolved. I can stay in fullscreen for multiple episodes and it will scrobble the updates flawlessly (Just tested this with Sora Yori mo Tooi Basho).
I only ever have one single Crunchyroll tab open, although it was two Chrome windows, and some other tabs but I dont think those other tabs affect this in any way.

**Comment by JannisBecker** [comment]
Hm, it's hard to reproduce. Now this time, with "Poco's Udon World", it didn't work. It just doesnt want to scrobble the second episode. But that could be an entirely different issue. I don't have any error messages in the log though. I'll get back to you if I find out anything, maybe after examining the source code a bit.

**Comment by KnightDemons** [comment]
Not scrobbling episodes on Chrome for both Netflix and Crunchyroll for me..

**Comment by leonekmi** [comment]
Since the HTML5 player load the next episode page, Scrobbly can detect it now.
