### ISSUE TITLE
Request twist.moe

### ISSUE THREAD

**Issue by samjaninf** [leonekmi/scrobbly#21]
**What is the name of the website ?**
Anime Twist
twist.moe

**Do you know if the website has an open API (in case of anime list or datasource) ?**
I do not believe so, but the URL is easily parsable.

**Comment by leonekmi** [comment]
Hello, sorry for the late answer, with f56835274f2b29cc9bb16dda542bff4d5ddbd802, Anime Twist will be supported in a next release.
